In [13]:
# Import the dependencies.
import random
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from citipy import citipy

In [14]:
# Import the database
city_database_df = pd.read_csv(r'C:\Users\otrin\OneDrive\Desktop\Git\World_Weather_Analysis\weather_data\WeatherPy_database.csv')

In [45]:
# Define column order as "new_order"
new_order = ["City", "Country", "Date", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Rain", "Snow"]

# Create new order for columns

city_database_df = city_database_df[new_order]

In [46]:
#Ask for min/max temp, rain and snow inputs
min_temp = float(input("What is the minimum acceptable temperature? "))
max_temp = float(input("What is the maximum acceptable temperature? "))
rain = input("Do you want it to be raining? y/n ")
snow = input("Do you want it to be snowing? y/n ")

What is the minimum acceptable temperature? 70
What is the maximum acceptable temperature? 90
Do you want it to be raining? y/n y
Do you want it to be snowing? y/n n

In [47]:
if rain == 'n' and snow == 'n':
    #filter the datateset to find the cities with no rain and no snow
    preferred_cities_df = city_database_df[(city_database_df["Max Temp"] <= max_temp) & \
                                           (city_database_df["Max Temp"] >= min_temp) & \
                                           (city_database_df["Rain"] == 0) & \
                                           (city_database_df["Snow"] == 0)]
elif rain == 'y' and snow == 'n':
    #filter the datateset to find the cities with rain and no snow
    preferred_cities_df = city_database_df[(city_database_df["Max Temp"] <= max_temp) & \
                                           (city_database_df["Max Temp"] >= min_temp) & \
                                           (city_database_df["Rain"] > 0) & \
                                           (city_database_df["Snow"] == 0)]
elif rain == 'n' and snow == 'y':
    #filter the datateset to find the cities with rain and no snow
    preferred_cities_df = city_database_df[(city_database_df["Max Temp"] <= max_temp) & \
                                           (city_database_df["Max Temp"] >= min_temp) & \
                                           (city_database_df["Rain"] == 0) & \
                                           (city_database_df["Snow"] > 0)]
else:
    #filter the datateset to find the cities with rain and no snow
    preferred_cities_df = city_database_df[(city_database_df["Max Temp"] <= max_temp) & \
                                           (city_database_df["Max Temp"] >= min_temp) & \
                                           (city_database_df["Rain"] > 0) & \
                                           (city_database_df["Snow"] > 0)]
preferred_cities_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain,Snow
0,Kavieng,PG,2020-06-28 16:18:42,-2.57,150.80,82.53,79,35,12.33,1.25,0
9,Namatanai,PG,2020-06-28 16:18:52,-3.67,152.43,79.50,79,77,6.87,0.77,0
20,Odiongan,PH,2020-06-28 16:20:24,12.40,121.99,79.93,83,100,11.74,0.68,0
22,Albany,US,2020-06-28 16:17:42,42.60,-73.97,71.60,83,90,4.70,0.25,0
51,Ivanteyevka,RU,2020-06-28 16:20:25,55.97,37.92,75.99,60,46,8.95,0.46,0
67,Hede,CN,2020-06-28 16:20:25,33.77,120.25,71.19,95,95,13.40,4.17,0
76,Tamandare,BR,2020-06-28 16:20:26,-8.76,-35.10,78.44,81,53,11.65,0.78,0
81,Daru,PG,2020-06-28 16:20:26,-9.08,143.21,77.85,86,97,15.39,0.14,0
96,Bonthe,SL,2020-06-28 16:20:26,7.53,-12.51,80.49,82,85,11.50,1.48,0
111,Wewak,PG,2020-06-28 16:20:27,-3.55,143.63,80.06,84,97,8.08,0.75,0

In [48]:
preferred_cities_df.count()

City          48
Country       48
Date          48
Lat           48
Lng           48
Max Temp      48
Humidity      48
Cloudiness    48
Wind Speed    48
Rain          48
Snow          48
dtype: int64

In [49]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"

# Export the City_Data into a CSV.
preferred_cities_df.to_csv(output_data_file, index_label="City_ID")

In [55]:
#import dependencies
import requests
import gmaps

#Import API key
from config import g_key

# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

# Get the maximum temperature.
max_temp = preferred_cities_df["Max Temp"]
temps = []
#using a for loop you can also use a list comprehension 
for temp in max_temp:
    temps.append(max(temp, 0))
    
# Heatmap of temperature
# Get the latitude and longitude.
locations = preferred_cities_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = preferred_cities_df["Max Temp"]
# Assign the figure variable. adding center and zoom variables
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable, improve max intensity, point radius, dissipation = False (default is true).
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [56]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp    Lat     Lng Hotel Name
0        Kavieng      PG     82.53  -2.57  150.80
9      Namatanai      PG     79.50  -3.67  152.43
20      Odiongan      PH     79.93  12.40  121.99
22        Albany      US     71.60  42.60  -73.97
51   Ivanteyevka      RU     75.99  55.97   37.92
67          Hede      CN     71.19  33.77  120.25
76     Tamandare      BR     78.44  -8.76  -35.10
81          Daru      PG     77.85  -9.08  143.21
96        Bonthe      SL     80.49   7.53  -12.51
111        Wewak      PG     80.06  -3.55  143.63

In [68]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {
        "radius": 5000,
        "types": "lodging",
        "key": g_key,
        "location": f"{lat},{lng}"}
    
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [69]:
print(hotels)

{'html_attributions': [], 'results': [{'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 7.617223000000001, 'lng': -71.4939333}, 'viewport': {'northeast': {'lat': 7.618581480291502, 'lng': -71.49253501970848}, 'southwest': {'lat': 7.615883519708498, 'lng': -71.4952329802915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png', 'id': '74c0ee82fea2ac6b35e256db39b47c93662759cc', 'name': 'Casa 7 Punta de Piedra', 'photos': [{'height': 720, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113342181511111625635">jose gerardo jauregui serrano</a>'], 'photo_reference': 'CmRaAAAAPOjIwYMmXtqtWk8xvLQZJ3SK3F4_LAnR2hiKIc6NZNYrz-CACf7slWoxNz1tr7FBaYDz42ZqKTL0IhpHzlI91-5TIZ2Orkyc1h27M7wZL-b8breAs7gFvCZhQNOp8vwCEhD3jarXTTgSXYyFpDrfP0q1GhStspEAXHTSXDLXgThCv2qJwm8rrA', 'width': 1280}], 'place_id': 'ChIJ-zWlI9CTZY4R1EpG0_wSqe8', 'plus_code': {'compound_code': 'JG84+VC Ramón Ignacio Méndez, Barinas, Venezuela', 'global_code': '67VCJG84+VC'}, 'reference': 'ChIJ-zWlI9CTZY4R1EpG0_wSqe8', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'vicinity': 'Carretera Barinas - San Cristóbal'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 7.6243857, 'lng': -71.5156488}, 'viewport': {'northeast': {'lat': 7.625792680291503, 'lng': -71.51426171970849}, 'southwest': {'lat': 7.623094719708498, 'lng': -71.5169596802915}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png', 'id': '73bdcd3c5c59a89f55e7660e956f813d9c175202', 'name': 'HOTEL MONTAÑA ANDINA CA', 'opening_hours': {'open_now': True}, 'photos': [{'height': 4128, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116813422641645935399">golfan perez</a>'], 'photo_reference': 'CmRaAAAAPF1ilrjD_XjjAMMp1fVm3SUsCThAk_gmkdwerjvRB5Iw5BA5jfjeaYDtWvEqyLGdRgTLvTQfiQ3wg57rN9xOuTpCHLuNzeV1QNacpwA3rDZv1DKmHPrYXtot9-n5P3t0EhDc2kUN1XnemqSpZ6Q742gzGhSdqomEVGCJ8-SQkAxEELZJabAebQ', 'width': 3096}], 'place_id': 'ChIJ9eXjYrOTZY4Rewl4WJgcBKY', 'plus_code': {'compound_code': 'JFFM+QP Abejales, Táchira, Venezuela', 'global_code': '67VCJFFM+QP'}, 'rating': 3.8, 'reference': 'ChIJ9eXjYrOTZY4Rewl4WJgcBKY', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 49, 'vicinity': 'Abejales'}, {'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 7.5803072, 'lng': -71.4715386}, 'viewport': {'northeast': {'lat': 7.581656580291502, 'lng': -71.47018956970851}, 'southwest': {'lat': 7.578958619708497, 'lng': -71.47288753029152}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png', 'id': '2a86499ac34c74137c0f642d490db58033a890d9', 'name': 'Hacienda Los Almendros Agroturismo', 'opening_hours': {'open_now': True}, 'photos': [{'height': 2448, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115177672004496155393">jonathan dominguez chacon</a>'], 'photo_reference': 'CmRaAAAA18GhPiYIjEqKjTISoYgbBeABkKX0asdE7H-RsmaZGs5SELLX6prldOkGQ5LcbJeGQ_eJU1qGI_uRkyaxKbghfN2MOTnx3SmUMJcTHNGztAAYf7QYcgG6eaXKpJjbbl3rEhCLK6eO0Y2hqST17GwWbOiBGhTyEphQbuQEoEx6SiGxMS52g9ysQw', 'width': 3264}], 'place_id': 'ChIJ0WeZ932RZY4RPPvlxmgtILw', 'plus_code': {'compound_code': 'HGJH+49 La Pedrera, Táchira, Venezuela', 'global_code': '67VCHGJH+49'}, 'rating': 5, 'reference': 'ChIJ0WeZ932RZY4RPPvlxmgtILw', 'scope': 'GOOGLE', 'types': ['lodging', 'point_of_interest', 'establishment'], 'user_ratings_total': 26, 'vicinity': 'San Antonio de Caparo, La Pediera'}], 'status': 'OK'}

In [70]:
len(hotels["results"])

3

In [72]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Kavieng,PG,82.53,-2.57,150.80,Nusa Island Retreat
9,Namatanai,PG,79.50,-3.67,152.43,Namatanai Hotel
20,Odiongan,PH,79.93,12.40,121.99,LFH Suite Promenade
22,Albany,US,71.60,42.60,-73.97,
51,Ivanteyevka,RU,75.99,55.97,37.92,New Slides
67,Hede,CN,71.19,33.77,120.25,Vienna 3 Best Hotel Sheyang Jiefang Rd
76,Tamandare,BR,78.44,-8.76,-35.10,Pousada 100 Passos
81,Daru,PG,77.85,-9.08,143.21,New century hotel
96,Bonthe,SL,80.49,7.53,-12.51,Bonthe Holiday Village
111,Wewak,PG,80.06,-3.55,143.63,In Wewak Boutique Hotel
112,Marki,PL,87.01,52.32,21.10,Hotel Złote Dęby
117,Atuona,PF,79.63,-9.80,-139.03,Villa Enata
137,Kapaa,US,73.40,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
143,Kankon,IN,81.52,15.02,74.02,Palolem Beach Resort
186,Yining,CN,77.43,29.04,114.56,Xiushui Hotel
205,Tucupita,VE,87.49,9.06,-62.05,Hotel Tucupita Su​ite C.A.
213,Mangan,IN,77.22,27.52,88.53,"Dzongu Lee, Home Stay"
244,Gigmoto,PH,79.93,13.78,124.39,Cj's Travellers Inn
246,Asau,RO,77.00,46.43,26.40,Casa Mika Ciobanus
247,Marawi,PH,73.99,8.00,124.29,Derogongan Residence
248,Veydelevka,RU,74.44,50.15,38.45,Po Foto
257,Salinopolis,BR,84.25,-0.61,-47.36,Hotel Salinópolis
258,Alappuzha,IN,75.00,9.49,76.33,Panoramic Sea Resort
278,Sinnamary,GF,83.05,5.38,-52.95,ALETHEIA Appartement Sinnamary
286,Akyab,MM,82.36,20.15,92.90,Hotel Memory
313,Coari,BR,87.62,-4.08,-63.14,HOTEL ALEX FLAT
314,Nhamunda,BR,82.62,-2.19,-56.71,Pousada Da Praia
321,Mozhaysk,RU,70.86,55.50,36.03,Country house U Ivanicha
330,Palu,ID,74.73,-0.89,119.87,Hotel Santika Palu
332,La Primavera,CO,74.68,5.49,-70.41,La Riviera Hotel Colonial
334,Huilong,CN,79.00,31.81,121.66,Hilton Garden Inn Qidong
338,Bengkulu,ID,78.03,-3.80,102.27,Grage Hotel Bengkulu
351,Matara,LK,80.53,5.95,80.54,Amaloh Boutique Resort
367,Ambon,ID,79.00,-3.70,128.18,Swiss-Belhotel Ambon
370,Mitu,CO,75.74,1.20,-70.17,
375,Bac Lieu,VN,81.99,9.29,105.72,Khách sạn Sài Gòn Bạc Liêu
385,Savannah Bight,HN,82.24,16.45,-85.85,Villa on Dunbar Rock
397,Maragogi,BR,78.84,-9.01,-35.22,Salinas do Maragogi All Inclusive Resort
398,Sapa,PH,78.37,5.15,120.32,
445,Piacabucu,BR,80.47,-10.41,-36.43,Piaçabuçu News
484,Kholm-Zhirkovskiy,RU,74.05,55.52,33.47,Gostinitsa Kholm
496,Itacoatiara,BR,84.70,-3.14,-58.44,BBB Rooms Centro Itacoatiara AM
510,Axim,GH,78.31,4.87,-2.24,AXIM BEACH RESORT AND SPA
518,Chekhov,RU,73.40,55.14,37.47,Cottage Edu v gosti
525,Koryukivka,UA,72.84,51.77,32.25,Polissya
529,Tabuk,PH,75.56,17.42,121.44,Grand Zion Garden Resort Hotel
541,Carmo,BR,72.27,-21.93,-42.61,Pousada do Carmo
542,Punta De Piedra,VE,78.49,7.62,-71.49,Casa 7 Punta de Piedra

In [73]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [74]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [75]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))